const menu = [
  {
    id: 1,
    title: 'Tost',
    category: 'Kahvalti',
    price: 54.00,
    img: './images/tost.jpg',
    desc: `Kahvaltınıza tat katıcak malzemesi bol bol olan efsane bi'dolu tost`,
  },
  {
    id: 2,
    title: 'Ciğer',
    category: 'Ana Yemek',
    price: 67.99,
    img: './images/ciger.jpg',
    desc: `Edirneli ustaların ellerinden edirnein meşhur ciğeri `,
  },
  {
    id: 3,
    title: 'Ev Yapımı Soğuk Çay',
    category: 'Soguk Icecek',
    price: 27.99,
    img: './images/Ev Yapımı Soğuk Çay.jpg',
    desc: `Kendi demlememiz olan karadeniz eşsiz çaylarından yaptığımız yaza damga vuran efsane soğuk çay`,
  },
  {
    id: 4,
    title: 'Serpme Kahvalti',
    category: 'Kahvalti',
    price: 140.00,
    img: './images/item-4.jpg',
    desc: `Vanin meshur serpe kahvaltisi varsayilan olarak 2 kisilik servis edilir. `,
  },
  {
    id: 5,
    title: 'Kofte',
    category: 'Ana Yemek',
    price: 55.99,
    img: './images/kofte.jpg',
    desc: `Kendi ozel baharatimizla harmanlanmis kofte ve gununde kendi uretimimiz olan ekmek ile servis edilir`,
  },
  {
    id: 6,
    title: 'Limonata',
    category: 'Soguk Icecek',
    price: 26.99,
    img: './images/limonata.jpg',
    desc: `Gununda taze ellerimizle topladigimiz gunluk sıkılmıs limonata`,
  },
  {
    id: 7,
    title: 'İçli Köfte',
    category: 'Ara Sicak',
    price: 29.99,
    img: './images/icli.jpg',
    desc: `Kendi yetiştiridğimiz kuzulardan yaptığımız iç harçla hazırlanan biricik içli köfte`,
  },
  {
    id: 8,
    title: 'Pide',
    category: 'Ana Yemek',
    price: 98.50,
    img: './images/pide.jpg',
    desc: `Ustamızın el emeği göz nuru olan yedikçe yetirten pide `,
  },
  {
    id: 9,
    title: 'Çay',
    category: 'Sicak Icecek',
    price: 23.00,
    img: './images/cay.jpg',
    desc: `Ülkemizin adeta çay ocağı olan karadenizimizden toplanmış çay yapraklarıyla demlenir`,
  },
  {
    id: 10,
    title: 'Paçanga Böreği',
    category: 'Ara Sicak',
    price: 23.00,
    img: './images/pacanga.jpg',
    desc: `Anne eli değmiş aynı tat aynı sıcaklıkla servis ettiğimiz biricik paçangamız`,
  },
];
export default menu;
